on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 3
      - uses: uses: namoshek/rabbitmq-github-action@v1
        with:
          version: '3.8.9'
      - run: go test -count=1 -v ./...
